- packages/rearch/lib/src/side_effects.dart
- packages/rearch/test/basic_test.dart
- packages/rearch/test/side_effects.dart
- packages/rearch/test/util.dart
> feat: add invalidatableFuture side effect

- packages/flutter_rearch/lib/src/widgets/consumer.dart
- packages/rearch/lib/src/impl.dart
- packages/rearch/test/basic_test.dart
> feat: handle not used across async gap assertions

- packages/rearch/lib/rearch.dart
- packages/rearch/lib/src/impl.dart
- packages/rearch/test/basic_test.dart
> fix: remove the generic on _CapsuleManager to allow capsule upcasts

- packages/rearch/lib/experimental.dart
- packages/rearch/lib/src/side_effects.dart
- packages/rearch/lib/src/types.dart
- packages/rearch/test/side_effects_test.dart
> feat: add experimental hydrate side effect

- packages/flutter_rearch/lib/src/widgets/consumer.dart
- packages/rearch/lib/rearch.dart
- packages/rearch/lib/src/impl.dart
- packages/rearch/lib/src/side_effects.dart
- packages/rearch/test/side_effects_test.dart
> fix: add side effect mutations to rebuilds

- packages/flutter_rearch/example/integration_test/todos_test.dart
- packages/flutter_rearch/example/linux/.gitignore
- packages/flutter_rearch/example/linux/CMakeLists.txt
- packages/flutter_rearch/example/linux/flutter/CMakeLists.txt
- packages/flutter_rearch/example/linux/flutter/generated_plugin_registrant.cc
- packages/flutter_rearch/example/linux/flutter/generated_plugin_registrant.h
- packages/flutter_rearch/example/linux/flutter/generated_plugins.cmake
- packages/flutter_rearch/example/linux/main.cc
- packages/flutter_rearch/example/linux/my_application.cc
- packages/flutter_rearch/example/linux/my_application.h
- packages/flutter_rearch/example/pubspec.yaml
- packages/flutter_rearch/lib/src/side_effects/animation.dart
> ci: add todos app integration test

- packages/rearch/lib/src/side_effects.dart
- packages/rearch/test/side_effects_test.dart
> feat: add replay state side effect

- packages/flutter_rearch/lib/src/side_effects.dart
> feat: add FocusNode related widget side effects

- .github/dependabot.yaml
- examples/scorus/lib/game_management.dart
- examples/scorus/lib/main.dart
- examples/scorus/lib/score.dart
- examples/scorus/lib/serving_player.dart
- examples/scorus/lib/volley.dart
- examples/scorus/pubspec.yaml
> docs(example): add pickleball score tracking example

- packages/rearch/lib/rearch.dart
- packages/rearch/lib/src/impl.dart
- packages/rearch/test/basic_test.dart
> feat: add assertion to ensure rebuild isn't called during a build

- examples/scorus/test/score_test.dart
> test: add scorus unit test

- README.md
> docs: update outdated parts of README

- packages/flutter_rearch/lib/src/widgets/consumer.dart
- packages/flutter_rearch/test/widgets_test.dart
> fix: rebuild RearchElement when its widget updates

- packages/flutter_rearch/lib/src/widgets/consumer.dart
- packages/flutter_rearch/test/widgets_test.dart
> fix: prevent premature idempotent capsule disposal

- packages/rearch/lib/rearch.dart
- packages/rearch/lib/src/capsule_warm_up.dart
- packages/rearch/test/basic_test.dart
Adds `capsuleContainer.warmUp(capsules)` as discussed in https://github.com/GregoryConrad/rearch-dart/discussions/125.
> feat: introduce `container.warmUp` extension method

- packages/flutter_rearch/lib/src/widgets/capsule_warm_up.dart
- packages/flutter_rearch/test/widgets_test.dart
> test: add unit tests for capsule warm up extension

- packages/flutter_rearch/test/side_effects_test.dart
- packages/rearch/lib/src/side_effects.dart
> fix: correct use.stream/future cancellation code

- packages/flutter_rearch/lib/src/widgets/consumer.dart
> fix: add workaround for flutter hot reload bug

- packages/rearch/lib/src/side_effects.dart
- packages/rearch/test/side_effects_test.dart
> refactor: deprecate old state side effects

- packages/rearch/lib/experimental.dart
> feat: add experimental dynamic capsules side effect

- packages/rearch/lib/experimental.dart
- packages/rearch/test/basic_test.dart
- packages/rearch/test/side_effects_test.dart
Adds two new experimental functions that enable easier capsule creation.
> feat: add experimental `capsule`/`dynamicCapsule`

- examples/weather_app/test/basic_test.dart
- packages/rearch/lib/rearch.dart
- packages/rearch/lib/src/impl.dart
- packages/rearch/test/basic_test.dart
- packages/rearch/test/util.dart
> feat: stabilize and improve ergonomics of MockableContainer

- packages/rearch/lib/experimental.dart
- packages/rearch/test/side_effects_test.dart
> feat: introduce new experimental dynamic capsule syntax

- README.md
- examples/hevy_smolov_jr/lib/api/raw_hevy_api.dart
- examples/hevy_smolov_jr/lib/api/wrapped_hevy_api.dart
- examples/hevy_smolov_jr/lib/shared_prefs.dart
- examples/hevy_smolov_jr/lib/steps/exercise_selection.dart
- packages/rearch/lib/experimental.dart
- packages/rearch/lib/rearch.dart
- packages/rearch/test/basic_test.dart
> feat: add `capsule` capsule creation convenience

- examples/hevy_smolov_jr/lib/main.dart
- examples/hevy_smolov_jr/lib/smolov_jr_config/config.dart
- examples/hevy_smolov_jr/lib/steps/confirmation_creation.dart
- examples/hevy_smolov_jr/lib/steps/exercise_selection.dart
- examples/hevy_smolov_jr/lib/steps/program_config.dart
- packages/flutter_rearch/lib/experimental.dart
- packages/flutter_rearch/test/injection_test.dart
> feat: add experimental `RearchInjection` widget for scoped state

- packages/rearch/lib/src/side_effects.dart
- packages/rearch/test/basic_test.dart
- packages/rearch/test/side_effects_test.dart
> fix: memoize the use.lazyData getter across builds
